name 'gcc-puppet'
version '0.2.0'
source 'git://github.com/an0nym0use/gcc-puppet.git'
author 'an0nym0use'
license 'Apache 2.0'
summary 'module for installing gcc build utils'
description 'module for installing gcc build utils'
project_page 'https://github.com/an0nym0use/gcc-puppet/'
dependency 'puppetlabs/stdlib', '>=2.0'

